version: '3'

services:

  postgres:
    container_name: postgres-container
    depends_on:
      - fluentd
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P0stgres
      - POSTGRES_DB=tourreserve
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "192.168.99.100:24224"
        tag: "docker.{{.Name}}"

  maven:
    container_name: maven-container
    build:
      context: .
      dockerfile: ./docker/maven/Dockerfile
    tty: true
    volumes:
      - ./terasoluna:/home/root/terasoluna

  tomcat:
    container_name: tomcat-container
    depends_on:
      - postgres
    image: tomcat:9.0.30-jdk11-openjdk
    volumes:
      - ./terasoluna:/root/terasoluna
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "192.168.99.100:24224"
        tag: "docker.{{.Name}}"

  httpd:
    container_name: httpd-container
    depends_on:
      - tomcat
    build:
      context: .
      dockerfile: ./docker/httpd/Dockerfile
    ports:
      - "10080:80"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "192.168.99.100:24224"
        tag: "docker.{{.Name}}"



  elasticsearch:
    container_name: elasticsearch-container
    build:
      context: .
      dockerfile: ./docker/elasticsearch/Dockerfile
    ports:
      - "9200:9200"
  
  kibana:
    container_name: kibana-container
    image: kibana:5.6.16
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch

  fluentd:
    container_name: fluentd-container
    build:
     context: .
     dockerfile: ./docker/fluentd/Dockerfile
    ports:
      - "24224:24224"
      - "24220:24220"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch
