apiVersion: v1
kind: Pod
metadata:
  name: terasoluna
spec:
  containers:

  - name: tomcat-container
    image: tomcat:9.0.30-jdk11-openjdk
    env:
    ports:
    - containerPort: 8080

  - name: httpd-container
    image: httpd:2.4.41
    ports:
    - containerPort: 80