apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: terasoluna
  labels:
    app: terasoluna

spec:
  replicas: 3
  selector:
    matchLabels:
      app: terasoluna

  template:
    metadata:
      labels:
        app: terasoluna
    spec:
      containers:
      - name: tomcat-container
        image: tomcat:9.0.30-jdk11-openjdk
        env:
        ports:
        - containerPort: 8080
      - name: httpd-container
        image: httpd:2.4.41
        ports:
        - containerPort: 80
